### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [sparkfun/pxt-gamer-bit#5]
Hi @sparkfun,

As you might have seen from https://github.com/microsoft/pxt-microbit/issues/3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer. 

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (link to codal-microbit issue).

> 2. Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

**Comment by microbit-pauline** [comment]
@AndyEngland521 and @pelikhan. I have received a ticket through the Foundation's support desk today. The user has a micro:bit V2 and a gamer:bit. They are getting an error code. I believe that Joe Finney but a fix in Codal version 0.2.34 in November. is this Codal version in MakeCode?

@AndyEngland521 Does Sparkfun need to do something on this ticket?

**Comment by microbit-mark** [comment]
@loricrotser is this fixed by the latest release?

**Comment by loricrotser** [comment]
I believe this was actually fixed by the updated [MicroBit Button constructor fix here](https://github.com/lancaster-university/codal-microbit-v2/commit/5e3836079b009d3a36c1685af06049435b49539c). I built a local server and tested this extension against v1.5 and v2 of the micro:bit and all worked as expected. Let me know if there's anything else I need to do here.

**Comment by aktivo** [comment]
If i add this extension to MakeCode project and upload to Micro:bit v2.21, micro:bit show error 927.

**Comment by loricrotser** [comment]
@aktivo We are dependent on the micro:bit builds and for some reason this one has be re-marked as not working, even though it does. We have added a locally built extension download to our tutorial that you can use while we wait on the external processes. 

Please check here: https://learn.sparkfun.com/tutorials/microarcade-kit-experiment-guide/troubleshooting-the-extension

If you continue to have issues with the extension, please reach out to SparkFun's tech support team and work directly with them. 

Thank you!

**Comment by jaustin** [comment]
Let's resolve this in MakeCode properly, though. @loricrotser do you know whether this stopped working after an update, or some specific other change? If you have it working locally, we should be able to enable it in MakeCode

**Comment by loricrotser** [comment]
The original failure was fixed by the [MicroBit Button constructor fix](https://github.com/lancaster-university/codal-microbit-v2/commit/5e3836079b009d3a36c1685af06049435b49539c). I tested micro:bits v1.5 and v2 against this and everything worked for me. I re-tested again some months ago and everything still worked as expected. To my knowledge this is fixed.
